// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCRCALmPB0hUA3WhpRMP5k2Z_UdTt6FiA0',
    appId: '1:479183496619:web:38e4e6b66acc237f971eee',
    messagingSenderId: '479183496619',
    projectId: 'fir-flutter-codelab-d4b29',
    authDomain: 'fir-flutter-codelab-d4b29.firebaseapp.com',
    storageBucket: 'fir-flutter-codelab-d4b29.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA-0xMmFLQ8RQJLBXdtIbaFkjcqaTSAoAY',
    appId: '1:479183496619:android:6f6fb915ae6d4962971eee',
    messagingSenderId: '479183496619',
    projectId: 'fir-flutter-codelab-d4b29',
    storageBucket: 'fir-flutter-codelab-d4b29.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDxswPV-RXz1i9WvVjhwzFSAze_F5cVEVE',
    appId: '1:479183496619:ios:a38862d8d6e40f3a971eee',
    messagingSenderId: '479183496619',
    projectId: 'fir-flutter-codelab-d4b29',
    storageBucket: 'fir-flutter-codelab-d4b29.appspot.com',
    iosBundleId: 'com.example.authApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDxswPV-RXz1i9WvVjhwzFSAze_F5cVEVE',
    appId: '1:479183496619:ios:20e7badb26221ca5971eee',
    messagingSenderId: '479183496619',
    projectId: 'fir-flutter-codelab-d4b29',
    storageBucket: 'fir-flutter-codelab-d4b29.appspot.com',
    iosBundleId: 'com.example.authApp.RunnerTests',
  );
}
